### ISSUE TITLE
Clover patches?

### ISSUE THREAD

**Issue by scerazy** [insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12#1]
Possible to make Clover hex edits instead of replacement of the whole kext? (which would be more OS update friendly)

I suppose the instructions are not fully correct, one should use for that cloverHDA with vanilla AppleHDA & clover edits (there is no need for patched AppleHDA!)

**Comment by insanelydeepak** [comment]
> I suppose the instructions are not fully correct, one should use for that cloverHDA with vanilla AppleHDA & clover edits (there is no need for patched AppleHDA!)
Yes you are right , Clover Patches means you never need to do binary patch again and again
