### ISSUE TITLE
Audio device not detecting (macOS 10.13.2)

### ISSUE THREAD

**Issue by nikhilpal2705** [insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12#12]
Tried every method in Dell Inspiron 3542 but audio devices not detecting.
Most of the methods shows "No codec found"(even show Jarvis of AppleHDA patcher).
Dell website shows Realtek ALC3223 High-Definition (HD) Audio for my device and I'm using ALC255.

DCPIManager shows this:
![screen shot 2018-01-31 at 5 41 12 pm](https://user-images.githubusercontent.com/13183708/35622493-07d1d6fc-06ae-11e8-84d7-dac9f5d3c904.png)

[codec_dump.txt](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/1681554/codec_dump.txt)

**Comment by insanelydeepak** [comment]
Hi 
above is HDMI Codec which is not usefull 
try to get this way 

`How to get Codec Dump :

 1. Use Ubuntu or Any Version of Linux Distro (Note : Use the latest version of Linux and Alsa drivers )
 2. Open Terminal and copy paste below Code :
  ~/Desktop && mkdir CodecDump && for c in /proc/asound/card*/codec#*; do f="${c/\/*card/card}"; cat "$c" > CodecDump/${f//\//-}.txt; done && zip -r CodecDump.zip CodecDump
  
 3. On Desktop there’s a folder/file name Codec_dump
 4. Save this to safe place  
`

**Comment by nikhilpal2705** [comment]
Thanks for reply,
Now i got 2 codec dump and useful one is attached here.
[codec_dump.txt](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/1691614/codec_dump.txt)

**Comment by insanelydeepak** [comment]
osx version ?

**Comment by nikhilpal2705** [comment]
10.13.2 build 17C88

**Comment by insanelydeepak** [comment]
try this, use layout 13
[AppleHDA-280.12-ALC255_v2.zip](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/1691936/AppleHDA-280.12-ALC255_v2.zip)

**Comment by nikhilpal2705** [comment]
Not working, tried adding 13 in audio inject of config.plist and also with DSDT patch.

**Comment by insanelydeepak** [comment]
provide these files 
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/blob/master/TroubleShoot/Troubleshoot%20Reporting.md

**Comment by nikhilpal2705** [comment]
Updated to 10.13.3 today.

[Troubleshoot Report.zip](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/1692593/Troubleshoot.Report.zip)

**Comment by insanelydeepak** [comment]
provide your DSDT and config.plist

**Comment by insanelydeepak** [comment]
apply IRQ patch too 
https://github.com/RehabMan/Laptop-DSDT-Patch/blob/5161c6645783326a62251df35e1f6522fae2d70b/system/system_IRQ.txt

**Comment by nikhilpal2705** [comment]
Thanks sir 😃 it worked, now audio is working after using your DSDT.
But headphone start making cracker sound after 30sec if no audio played(means if i keep headphone standby for 30s without playing any audio), also it's working at mono mode.

**Comment by insanelydeepak** [comment]
use CodecCommander + SSDT255

**Comment by nikhilpal2705** [comment]
Where can i get SSDT255?

**Comment by insanelydeepak** [comment]
> Where can i get SSDT255?
i will provide you one 

use this kext is enough 
https://bitbucket.org/RehabMan/os-x-eapd-codec-commander/downloads/

**Comment by nikhilpal2705** [comment]
A big thanks sir, now audio is working fine just like in windows system.

**Comment by insanelydeepak** [comment]
Great 
Enjoy Good Sound
