### ISSUE TITLE
Realtek ALC256 Support

### ISSUE THREAD

**Issue by Striker770** [insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12#16]
Hi @insanelydeepak 
I've a Laptop from ASUS and trying to make the Audio work. Any help?

**Comment by insanelydeepak** [comment]
Hi 
are you available to fix this ??

**Comment by Striker770** [comment]
Here's the Codec Dump.
[codec_dump.1.txt](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/2594984/codec_dump.1.txt)

**Comment by insanelydeepak** [comment]
OSX Version ??

**Comment by insanelydeepak** [comment]
try this 
use layout13
[AppleHDA-280.12-ALC256v3.zip](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/2595120/AppleHDA-280.12-ALC256v3.zip)

**Comment by Striker770** [comment]
> try this
> use layout13
> [AppleHDA-280.12-ALC256v3.zip](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/2595120/AppleHDA-280.12-ALC256v3.zip)

Okay. Trying and reporting. Upto what time will you be here?

**Comment by insanelydeepak** [comment]
i'm here for 5-6 hours then tomorrow

**Comment by Striker770** [comment]
Thanks man.

**Comment by Striker770** [comment]
Hi
I'm ready for tests.
Reporting it now.

**Comment by Striker770** [comment]
Used layout-ID=13, no Audio at all.

**Comment by insanelydeepak** [comment]
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/blob/master/TroubleShoot/Troubleshoot%20Reporting.md
