### ISSUE TITLE
Realtek ALC299 Support

### ISSUE THREAD

**Issue by Striker770** [insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12#17]
Hi @insanelydeepak
I've a Laptop from Dell and trying to make the Audio work. Any help?
Here's the Codec Dump
[codec_dump.txt](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/2683822/codec_dump.txt)
Thanks

**Comment by insanelydeepak** [comment]
OSX Version ?

**Comment by Striker770** [comment]
> OSX Version ?

10.14

**Comment by Striker770** [comment]
With the another post, the Headphones work but not the Internal Speakers

**Comment by insanelydeepak** [comment]
try this use layout 14 
[AppleHDA-282.10-ALC299_v3.zip](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/2693296/AppleHDA-282.10-ALC299_v3.zip)

**Comment by Striker770** [comment]
> try this use layout 14
> [AppleHDA-282.10-ALC299_v3.zip](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/2693296/AppleHDA-282.10-ALC299_v3.zip)

The Internal Speakers are working.
Heaphones works only when using EliteMacx86 script.
The Microphone shows as Internal Speakers.
Unable to use Keyboard using this AppleHDA

**Comment by insanelydeepak** [comment]
> The Internal Speakers are working
what about other input output's

> Heaphones works only when using EliteMacx86 script.
show me ??

> The Microphone shows as Internal Speakers.
> Unable to use Keyboard using this AppleHDA

this is strange , never heard keyboard issue with appleHDA 
try to use voodooPS2 keyboard kext

**Comment by Striker770** [comment]
Well, it happened.

**Comment by insanelydeepak** [comment]
please share all input/output details 

Speakers : ?
Headphone : ? 
Mic : Internal ?
Mic : External ?

**Comment by Ericarthurc** [comment]
> please share all input/output details , so i can complete it
> 
> Speakers : ?
> Headphone : ?
> Mic : Internal ?
> Mic : External ?

Could you help me with ALC299 on High Sierra?? I have a nvidia card, so I am staying on High Sierra until Mojave drivers are worked out. I tried the V3 with layout 14 in clover; but nothing is coming up in input or outputs.

**Comment by insanelydeepak** [comment]
@Ericarthurc  sure tomorrow , if you won't get reply ping me

**Comment by Ericarthurc** [comment]
> @Ericarthurc sure tomorrow , if you won't get reply ping me

okay, thank you so much

**Comment by Striker770** [comment]
> > The Internal Speakers are working
> 
> what about other input output's
> 
> > Heaphones works only when using EliteMacx86 script.
> 
> show me ??
> 
> > The Microphone shows as Internal Speakers.
> > Unable to use Keyboard using this AppleHDA
> 
> this is strange , never heard keyboard issue with appleHDA
> try to use voodooPS2 keyboard kext

Sorry for the late reply, been busy a lot.
Headphones do not work at all.
When executing the EliteMacx86 script, the Internal Microphone changes to Line In.

Sometimes, when booting to Windows and then back to Mac, keyboard stops working. Any idea about that?

**Comment by insanelydeepak** [comment]
> When executing the EliteMacx86 script, the Internal Microphone changes to Line In.

share with me 

> Sometimes, when booting to Windows and then back to Mac, keyboard stops working. Any idea about that?

i have no idea, i never hold a laptop only help others , better to ask at OSXLatitude or InsanelyMac

**Comment by insanelydeepak** [comment]
if you available and bug still exist let me know so we can fix it together

**Comment by Striker770** [comment]
> share with me

Here's the EliteMacx86 script.
https://www.elitemacx86.com/threads/fix-audio-distortion-when-using-headphones-on-laptops.185/

**Comment by Striker770** [comment]
> if you available and bug still exist let me know so we can fix it together

Sure.

**Comment by insanelydeepak** [comment]
> > share with me
> 
> Here's the EliteMacx86 script.
> https://www.elitemacx86.com/threads/fix-audio-distortion-when-using-headphones-on-laptops.185/

how someone took your work and not even mention a credit 

this script is not magic just a rip of version goodwin ALCPlufix 

ALCPlugFix me and goodwin we worked hard to make this possible bcoz codec commander wasn't working 

don't rely on it you still have to fix Pinconfig and Pathmaps nodes

**Comment by insanelydeepak** [comment]
what your current issue ? so we can fix it

**Comment by insanelydeepak** [comment]
read this 
https://osxlatitude.com/forums/topic/11316-how-to-fix-static-noisedistortioncrackling-sound-and-combojack-in-laptops/?tab=comments#comment-88515

**Comment by insanelydeepak** [comment]
re-open when you available , so i could get notified
