### ISSUE TITLE
Apple ALC898 on MSI GS40 Phantom

### ISSUE THREAD

**Issue by rkatuku** [insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12#3]
Hi,

Thank you for providing this patch. My Audio is detected in SR 10.12.2. But there is no sound from internal speakers, although microphone & headphones are working on Digital out with layout id 13. I have tried with all layout id's listed. And also sound from headphones is distorting a lot. Is there anything you could suggest is much appreciated.

I have MSI GS40 laptop, with Realtek ALC898 audio

Thanks You

**Comment by insanelydeepak** [comment]
use codec_commander , if still nothing happens then we need to debug issue

**Comment by rkatuku** [comment]
@insanelydeepak Awesome !!! Internal speaker detected after installing codec_commander and working fine

Thank You
