### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Lezardon** [insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12#5]
It does not work (nothing in sound panel). My config: Dell Inspiron 15 3521 with dual boot W10/Sierra 10.12, Clover 2.4.

**Comment by insanelydeepak** [comment]
what's your codec?

please post troubleshoot file 
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/blob/master/TroubleShoot/Troubleshoot%20Reporting.md

**Comment by Lezardon** [comment]
in DCPIManager, i have this:

![capture d ecran 2017-06-11 a 01 19 04](https://user-images.githubusercontent.com/5399462/27003070-47f2801c-4e1a-11e7-81bd-1be29c161a05.png)

**Comment by Lezardon** [comment]
No idea ?

**Comment by insanelydeepak** [comment]
you have to wait , im busy with other stuffs and will look when have time

**Comment by insanelydeepak** [comment]
hi can you post files again ?? 
not accessible now

**Comment by Lezardon** [comment]
I succeeded to get the sound working using HDAPAtcher 1.7. However, the volume is not so loud and I'm considering an anoher solution to get a perfect sound. I have got dump audio codec from Linux and realized that my sound codec is **not** ALC282 (as DPIManager reports) but an ALC3221. Does your kext could work with such codec ?
[codec_dump.txt](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/1082382/codec_dump.txt)

**Comment by insanelydeepak** [comment]
your codec is ALC282 
what your OSXVersion ? exact version like 10.12 or 10.12.1 etc

**Comment by Lezardon** [comment]
Thank you for your attention to my issue. You will find attached the troubleshooting report files.

[Troubleshooting files report.zip](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/1082872/Troubleshooting.files.report.zip)

**Comment by insanelydeepak** [comment]
try this 
use layout id = 13 

[AppleHDA-276.26-ALC282.zip](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/1083072/AppleHDA-276.26-ALC282.zip)

**Comment by Lezardon** [comment]
Thank you. i have tried several hours with this kext but no sound at all :-((. I have tried again HDAPatcher 1.7 but the volume is too low on both jack and internal speaker. And with AppleALC+Lilu the sound from jack is perfect but volume from internal speaker too low.

**Comment by insanelydeepak** [comment]
did you changes LayoutID ??

**Comment by Lezardon** [comment]
Yes, I did. But no sound at all :((

**Comment by insanelydeepak** [comment]
try it again and post troubleshoot files whole it installed

**Comment by Lezardon** [comment]
i have tried again with layout 13. But no sound. Here are my updated report files. Thank you for your help
[troubleshooting report.zip](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/1091920/troubleshooting.report.zip)
.

**Comment by insanelydeepak** [comment]
you driving me crazy , old version show 10.12 now 10.12.5 

what version is now ?

**Comment by Lezardon** [comment]
yes. correct and sorry for that :) I have recently updated to 10.12.5. Everything works well except sound :( Current version is 10.12.5 then.

**Comment by insanelydeepak** [comment]
try this AppleALC 
layout 13

[AppleALC.kext.zip](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/1093564/AppleALC.kext.zip)

**Comment by Lezardon** [comment]
Yes thank you. Any kext/DSDT patches to apply ?

**Comment by insanelydeepak** [comment]
no don't need anything , just use with Lilu 
layout 13 and vanilla appleHDA is must

**Comment by Lezardon** [comment]
I have installed these kexts and the sound came back... but with the same issue. Volume is only the half the one I get from my Windows session. I have uploaded 2 videos for you to see:
https://youtu.be/7MA-9vdgI7Q
https://youtu.be/BFt2qRjCwlg
Strangly, this issue come along with both these kexts and with the HDA patcher 1.8.

**Comment by insanelydeepak** [comment]
send your codec_dump

**Comment by Lezardon** [comment]
[codec_dump.txt](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/1094466/codec_dump.txt)

**Comment by Lezardon** [comment]
[codec_dump.txt](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/1094472/codec_dump.txt)

**Comment by insanelydeepak** [comment]
try this 
[Test282.zip](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/1094499/Test282.zip)

**Comment by insanelydeepak** [comment]
try this 
[282.zip](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/1097265/282.zip)

**Comment by Lezardon** [comment]
Thanks. It is the same than before. There is sound but with half volume only. It seems that the issue does not come from the kext ?

**Comment by insanelydeepak** [comment]
you are right issue is not with Kext 
you should perform fresh installation .may it help
