### ISSUE TITLE
No cloverHDA.plist for Conexant CX20590v1

### ISSUE THREAD

**Issue by augustosamame** [insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12#6]
Hi. I reached this point:

"Now apply patches from cloverHDA.plist to your Clover config.plist"

However there is no cloverHDA.plist in downloaded zip. Audio does not work so I'm guessing I'm missing a file? Thanks in advance for your help.

**Comment by insanelydeepak** [comment]
try this
[Conexant CX20590_v1.zip](https://github.com/insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12/files/1224908/Conexant.CX20590_v1.zip)

**Comment by insanelydeepak** [comment]
so I'm closing this issue till you available .
feel free to re-open whenever required
