### ISSUE TITLE
HP Probook 440 G4 - Conexant CX7700 Codex

### ISSUE THREAD

**Issue by agung2001** [insanelydeepak/Patched-AppleHDA-for-Mac-OS-Sierra-10.12#9]
My notebook is HP Probook 440 G4, with audio Conexant CX7700 codex. I think its still not support yet, hope the patch will support it soon...

**Comment by insanelydeepak** [comment]
Hi 

this codec is not in list 
plz provide codec dump so we can add it too

**Comment by agung2001** [comment]
ow its working, i try to use Conexant CX8200 with my 440 G4 and its working perfectly. Thank you man 💃
